### ISSUE TITLE
Roadmap to v1.0

### ISSUE THREAD

**Issue by xen0n** [xen0n/gosmopolitan#1]
* [x] lint `time.Local` usages
* [x] support marking certain types as escape hatches
* [x] ability to get integrated into`golangci-lint`
* [x] test suite
* [x] support checking non-Han script characters
* [x] translate README to Chinese

**Comment by xen0n** [comment]
All done since commit 3fca187, closing!
